# Generated by Django 4.0.3 on 2022-03-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_description_post_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='input',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
